# Generated by Django 5.1.7 on 2025-03-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('correo', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('compania', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.compania')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.persona')),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.termino')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_productos', to='facturacion.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_productos', to='productos.producto')),
            ],
        ),
    ]
