# Generated by Django 5.1.7 on 2025-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
